(() => {
const $=id=>document.getElementById(id);
const mount=$("gameMount"), result=$("result"), debug=$("debug");
let difficulty="normal", active=null, cleanup=()=>{};
const diff={easy:{w:9,mistakes:4,speed:.65},normal:{w:5,mistakes:3,speed:1},hard:{w:3,mistakes:2,speed:1.28},expert:{w:2,mistakes:2,speed:1.55}};
const modes=[
  ["dial","Manual Dial"],["tumblers","Tumblers"],["wave","Sound Wave"],["rings","Rotating Rings"],["nodes","Electronic Route"],["listen","Listen & Stop"],["deduction","Deduction"]
];
function setResult(msg,type="info"){result.textContent=msg;result.className="result "+type;$("hudStatus").textContent=msg||"Ready"}
function wrap(n,max=100){return((n%max)+max)%max} function d100(a,b){let d=Math.abs(a-b);return Math.min(d,100-d)}
function ri(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function shuffle(a){for(let i=a.length-1;i>0;i--){const j=ri(0,i);[a[i],a[j]]=[a[j],a[i]]}return a}
function title(name,sub){return `<h2 class="game-title">${name}</h2><p class="game-sub">${sub}</p>`}
function debugText(t){debug.textContent=t}
function setupTabs(){const host=$("modeTabs");modes.forEach(([id,name])=>{const b=document.createElement("button");b.className="mode-tab";b.textContent=name;b.dataset.mode=id;b.addEventListener("click",()=>load(id));host.appendChild(b)})}
function load(id){cleanup();cleanup=()=>{};active=id;document.querySelectorAll(".mode-tab").forEach(b=>b.classList.toggle("active",b.dataset.mode===id));$("hudMode").textContent=modes.find(x=>x[0]===id)[1];setResult("Ready","info");({dial:gameDial,tumblers:gameTumblers,wave:gameWave,rings:gameRings,nodes:gameNodes,listen:gameListen,deduction:gameDeduction}[id])()}

function gameDial(){
 let combo=[ri(0,99),ri(0,99),ri(0,99)],stage=0,mistakes=0,current=ri(0,99),dir=null,drag=false,lastA=0;const dirs=["left","right","left"],D=diff[difficulty];
 mount.innerHTML=title("Manual Combination Dial","Feel for stronger feedback and lock three numbers in Left → Right → Left order.")+`<div class="mini-hud"><span class="mini-pill" id="dStage"></span><span class="mini-pill" id="dMiss"></span></div><div class="dial-shell"><div id="dPulse" class="pulse"></div><button id="dialObj" class="dial" type="button"><div class="pointer"></div><div class="dial-center"><div id="dNum" class="dial-num"></div><div id="dDir" class="dial-dir"></div></div></button></div><div class="signal-row"><span>Signal</span><div class="meter"><div id="dSig"></div></div><b id="dSigTxt"></b></div><div class="action-row"><button id="dLeft" class="action">◀ Left</button><button id="dSet" class="action primary">Set Number</button><button id="dRight" class="action">Right ▶</button></div>`;
 const upd=()=>{if(stage>=3)return;$("dStage").textContent=`Stage ${stage+1}/3`;$("dMiss").textContent=`Mistakes ${mistakes}/${D.mistakes}`;$("dNum").textContent=String(current).padStart(2,"0");$("dDir").textContent=`TURN ${dirs[stage].toUpperCase()}`;const dist=d100(current,combo[stage]);const s=Math.max(0,Math.min(1,1-dist/23));$("dSig").style.width=(s*100)+"%";$("dSigTxt").textContent=s>.8?"Strong":s>.5?"Warm":s>.25?"Faint":"Cold";$("dPulse").style.boxShadow=`0 0 ${Math.round(s*32)}px rgba(255,255,255,${s*.25})`;debugText(`Answer: ${combo[0]} ←  ${combo[1]} →  ${combo[2]} ←`)};
 const move=x=>{if(stage>=3||mistakes>=D.mistakes)return;dir=x;current=wrap(current+(x==="right"?1:-1));upd()};
 $("dLeft").onclick=()=>move("left");$("dRight").onclick=()=>move("right");$("dSet").onclick=()=>{if(dir!==dirs[stage]){mistakes++;setResult("Wrong turn direction.","bad")}else if(d100(current,combo[stage])<=D.w){stage++;dir=null;if(stage===3){setResult("Safe opened.","good");$("dDir").textContent="OPEN"}else setResult("Click found. Reverse direction.","good")}else{mistakes++;setResult("No click at that number.","bad")}if(mistakes>=D.mistakes)setResult("Locked out.","bad");upd()};
 const dial=$("dialObj");function ang(e){let r=dial.getBoundingClientRect();return Math.atan2(e.clientY-r.top-r.height/2,e.clientX-r.left-r.width/2)*180/Math.PI}dial.onpointerdown=e=>{drag=true;lastA=ang(e);dial.setPointerCapture(e.pointerId)};dial.onpointermove=e=>{if(!drag)return;let a=ang(e),delta=a-lastA;if(delta>180)delta-=360;if(delta<-180)delta+=360;if(Math.abs(delta)>3){move(delta>0?"right":"left");lastA=a}};dial.onpointerup=()=>drag=false;dial.onpointercancel=()=>drag=false;upd();
}

function gameTumblers(){
 const n=difficulty==="easy"?4:difficulty==="normal"?5:6,D=diff[difficulty],target=50,band=difficulty==="easy"?11:difficulty==="normal"?8:difficulty==="hard"?6:4;let vals=Array.from({length:n},()=>ri(10,90)),moves=0;
 mount.innerHTML=title("Tumbler Alignment","Raise each pin into the shear line. Each control also nudges a neighbor, so plan the order.")+`<div class="mini-hud"><span class="mini-pill" id="tMoves"></span><span class="mini-pill">Pins ${n}</span></div><div class="tumbler-board" id="tBoard"></div><div class="tumbler-buttons" id="tBtns"></div>`;
 const board=$("tBoard"),btns=$("tBtns");for(let i=0;i<n;i++){board.insertAdjacentHTML("beforeend",`<div class="tumbler-col"><div class="sweet-band"></div><div class="pin" id="pin${i}"></div></div>`);const b=document.createElement("button");b.className="pad-btn";b.textContent=i+1;b.onclick=()=>tap(i);btns.appendChild(b)}
 function ok(v){return Math.abs(v-target)<=band}function tap(i){moves++;vals[i]=Math.min(96,vals[i]+(difficulty==="expert"?9:12));if(vals[i]>92)vals[i]=12;if(i+1<n)vals[i+1]=wrap(vals[i+1]+5,100);if(difficulty!=="easy"&&i>0)vals[i-1]=wrap(vals[i-1]+2,100);render();if(vals.every(ok))setResult(`All tumblers aligned in ${moves} moves. Safe opened.`,"good")}
 function render(){vals.forEach((v,i)=>{const p=$(`pin${i}`);p.style.bottom=`${v}%`;p.classList.toggle("ok",ok(v))});$("tMoves").textContent=`Moves ${moves}`;debugText(`Target band: ${target-band}–${target+band}\nPins: ${vals.join(", ")}`)}render();
}

function gameWave(){
 const D=diff[difficulty],targets=[ri(8,91),ri(8,91),ri(8,91)],dirs=[1,-1,1];let stage=0,pos=0,mistakes=0,raf,last=performance.now();const speed=(difficulty==="easy"?8:difficulty==="normal"?13:difficulty==="hard"?18:23);
 mount.innerHTML=title("Sound-Wave Scanner","Sweep the lock and watch the waveform. Stop where the mechanical resonance becomes strongest.")+`<div class="mini-hud"><span class="mini-pill" id="wStage"></span><span class="mini-pill" id="wMiss"></span></div><div class="wave-wrap"><svg class="wave-svg" viewBox="0 0 600 220" preserveAspectRatio="none"><polyline id="waveLine" fill="none" stroke="#cfd6dd" stroke-width="3" points=""/></svg><div class="scanner"><div id="scanPos" class="scanner-pos"></div></div><div id="scanTxt" class="scan-readout"></div></div><div class="action-row"><button id="waveLock" class="action primary">Lock Resonance</button></div>`;
 function draw(){let pts=[];const dist=d100(pos,targets[stage]??0),hot=Math.max(0,1-dist/24);for(let x=0;x<=600;x+=8){const y=110+Math.sin(x*.08+pos*.1)*18+Math.sin(x*.22)*8*hot+Math.sin(x*.47)*20*hot;pts.push(`${x},${y}`)}$("waveLine").setAttribute("points",pts.join(" "));$("scanPos").style.left=pos+"%";$("scanTxt").textContent=hot>.82?"Distinct double resonance":hot>.5?"Stronger vibration":hot>.22?"Faint mechanical noise":"Flat response";$("wStage").textContent=`Stage ${Math.min(stage+1,3)}/3`;$("wMiss").textContent=`Mistakes ${mistakes}/${D.mistakes}`;debugText(`Resonances: ${targets.join(", ")} | current ${pos.toFixed(1)}`)}
 function loop(t){const dt=(t-last)/1000;last=t;if(stage<3&&mistakes<D.mistakes){pos+=dirs[stage]*speed*dt;if(pos>=100){pos=100;dirs[stage]=-1}else if(pos<=0){pos=0;dirs[stage]=1}draw()}raf=requestAnimationFrame(loop)}
 $("waveLock").onclick=()=>{if(d100(pos,targets[stage])<=D.w+2){stage++;setResult(stage===3?"All resonances matched. Safe opened.":"Resonance locked.","good")}else{mistakes++;setResult("Wrong resonance.","bad")}if(mistakes>=D.mistakes)setResult("Alarmed / locked out.","bad");draw()};raf=requestAnimationFrame(loop);cleanup=()=>cancelAnimationFrame(raf);draw();
}

function gameRings(){
 const step=difficulty==="easy"?15:difficulty==="normal"?12:difficulty==="hard"?9:7;let a=[ri(0,35)*10,ri(0,35)*10,ri(0,35)*10],moves=0;const tol=difficulty==="easy"?16:difficulty==="normal"?11:difficulty==="hard"?7:5;
 mount.innerHTML=title("Rotating Ring Lock","Align all three notches at twelve o'clock. Moving one ring subtly shifts another.")+`<div class="mini-hud"><span class="mini-pill" id="rMoves"></span></div><div class="rings"><div id="ring0" class="ring one"></div><div id="ring1" class="ring two"></div><div id="ring2" class="ring three"></div><div class="ring-center"></div></div><div class="ring-controls" id="ringControls"></div>`;
 const rc=$("ringControls");for(let i=0;i<3;i++){const d=document.createElement("div");d.innerHTML=`<b>Ring ${i+1}</b><button class="action" data-i="${i}" data-d="-1">◀</button><button class="action" data-i="${i}" data-d="1">▶</button>`;rc.appendChild(d)}rc.querySelectorAll("button").forEach(b=>b.onclick=()=>turn(+b.dataset.i,+b.dataset.d));
 function delta0(x){x=wrap(x,360);return Math.min(x,360-x)}function turn(i,d){moves++;a[i]=wrap(a[i]+d*step,360);const neighbor=(i+1)%3;a[neighbor]=wrap(a[neighbor]-d*(difficulty==="easy"?0:step/3),360);render();if(a.every(x=>delta0(x)<=tol))setResult(`All notches aligned in ${moves} moves. Safe opened.`,"good")}
 function render(){a.forEach((x,i)=>$(`ring${i}`).style.transform=`rotate(${x}deg)`);$("rMoves").textContent=`Moves ${moves}`;debugText(`Angles: ${a.map(x=>x.toFixed(1)).join("°, ")}° | target 0° ±${tol}`)}render();
}

function gameNodes(){
 const hard=difficulty==="hard"||difficulty==="expert";const positions=[ [10,50],[26,22],[27,76],[47,35],[48,69],[68,20],[69,54],[71,84],[90,50] ];const alarmIds=hard?[4,6]:difficulty==="normal"?[6]:[];const edges=[[0,1],[0,2],[1,3],[2,3],[2,4],[3,5],[3,6],[4,6],[4,7],[5,8],[6,8],[7,8],[1,4],[5,6]];let selected=0,path=[0];
 mount.innerHTML=title("Electronic Safe Routing","Route power from START to VAULT without touching alarm nodes. Backtracking is allowed.")+`<div class="mini-hud"><span class="mini-pill" id="nPath"></span></div><div id="nodeBoard" class="node-board"></div><div class="action-row"><button id="nodeBack" class="action">Backtrack</button><button id="nodeClear" class="action">Reset Route</button></div>`;
 const board=$("nodeBoard");function lineGeom(a,b){const A=positions[a],B=positions[b],dx=B[0]-A[0],dy=B[1]-A[1],len=Math.hypot(dx,dy),ang=Math.atan2(dy,dx)*180/Math.PI;return `left:${A[0]}%;top:${A[1]}%;width:${len}%;transform:rotate(${ang}deg)`}
 edges.forEach(([a,b],i)=>board.insertAdjacentHTML("beforeend",`<div id="edge${i}" class="node-line" style="${lineGeom(a,b)}"></div>`));positions.forEach((p,i)=>{const b=document.createElement("button");b.className="node "+(i===0?"start":i===8?"goal":alarmIds.includes(i)?"alarm":"");b.style.left=p[0]+"%";b.style.top=p[1]+"%";b.textContent=i===0?"START":i===8?"VAULT":alarmIds.includes(i)?"ALARM":String(i);b.onclick=()=>pick(i);board.appendChild(b)});
 function adjacent(a,b){return edges.some(e=>(e[0]===a&&e[1]===b)||(e[0]===b&&e[1]===a))}function pick(i){if(i===selected)return;if(!adjacent(selected,i)){setResult("That node is not connected to your current route.","bad");return}if(alarmIds.includes(i)){setResult("Alarm node triggered. Route failed.","bad");return}path.push(i);selected=i;render();if(i===8)setResult("Power routed cleanly. Electronic safe opened.","good")}
 $("nodeBack").onclick=()=>{if(path.length>1){path.pop();selected=path[path.length-1];render()}};$("nodeClear").onclick=()=>{path=[0];selected=0;setResult("Route reset.","info");render()};
 function render(){board.querySelectorAll(".node").forEach((n,i)=>{n.classList.toggle("selected",i===selected);n.classList.toggle("connected",path.includes(i))});edges.forEach((e,i)=>{let active=false;for(let j=1;j<path.length;j++)if((e[0]===path[j-1]&&e[1]===path[j])||(e[1]===path[j-1]&&e[0]===path[j]))active=true;$(`edge${i}`).classList.toggle("active",active)});$("nPath").textContent="Route: "+path.join(" → ");debugText(`Alarm nodes: ${alarmIds.length?alarmIds.join(", "):"none"}\nValid edges: ${edges.map(e=>e.join("-" )).join(", ")}`)}render();
}

function gameListen(){
 const D=diff[difficulty],targets=[ri(12,88),ri(12,88),ri(12,88)];let stage=0,pos=0,dir=1,mistakes=0,raf,last=performance.now();const speed=18*D.speed,zone=D.w+3;
 mount.innerHTML=title("Listen & Stop","The dial sweeps automatically. Read the changing click rhythm and stop on the hidden sweet spot.")+`<div class="mini-hud"><span class="mini-pill" id="lStage"></span><span class="mini-pill" id="lMiss"></span></div><div class="listen-stage"><div class="listen-track"><div id="lZone" class="listen-zone hidden"></div><div id="lMarker" class="listen-marker"></div></div><div id="rhythm" class="rhythm"></div><div id="lText" class="scan-readout"></div></div><div class="action-row"><button id="lStop" class="action primary">STOP / Listen Here</button></div>`;
 function render(){const distance=d100(pos,targets[stage]??0),hot=Math.max(0,1-distance/24);$("lMarker").style.left=pos+"%";$("lStage").textContent=`Stage ${Math.min(stage+1,3)}/3`;$("lMiss").textContent=`Mistakes ${mistakes}/${D.mistakes}`;const rhythm=$("rhythm");rhythm.innerHTML="";for(let i=0;i<9;i++){const b=document.createElement("div");b.className="beat"+(hot>.72&&i%2===0?" hot":"");b.style.height=(8+Math.abs(Math.sin(i*1.7+pos*.1))*13+hot*(i%2===0?18:5))+"px";rhythm.appendChild(b)}$("lText").textContent=hot>.8?"Double-click rhythm":hot>.5?"Clicks tightening":hot>.25?"Occasional click":"Quiet";debugText(`Stops: ${targets.join(", ")} | current ${pos.toFixed(1)} | zone ±${zone}`)}
 function loop(t){const dt=(t-last)/1000;last=t;if(stage<3&&mistakes<D.mistakes){pos+=dir*speed*dt;if(pos>=100){pos=100;dir=-1}else if(pos<=0){pos=0;dir=1}render()}raf=requestAnimationFrame(loop)}
 $("lStop").onclick=()=>{if(d100(pos,targets[stage])<=zone){stage++;setResult(stage===3?"All three click rhythms found. Safe opened.":"Correct click rhythm.","good")}else{mistakes++;setResult("Wrong rhythm.","bad")}if(mistakes>=D.mistakes)setResult("Lockout triggered.","bad");render()};raf=requestAnimationFrame(loop);cleanup=()=>cancelAnimationFrame(raf);render();
}

function gameDeduction(){
 const maxGuesses=difficulty==="easy"?9:difficulty==="normal"?7:difficulty==="hard"?6:5;const secret=ri(0,99);let guesses=0,history=[];
 mount.innerHTML=title("Combination Deduction","Use limited guesses and feedback to narrow down the hidden two-digit number.")+`<div class="mini-hud"><span class="mini-pill" id="gCount"></span></div><div class="deduce"><div class="guess-row"><label for="guessInput"><b>Guess</b></label><input id="guessInput" type="number" inputmode="numeric" min="0" max="99" placeholder="00"></div><div class="action-row"><button id="guessBtn" class="action primary">Test Number</button></div><div id="history" class="history"></div></div>`;
 function clue(g){const delta=g-secret,ad=Math.abs(delta);if(ad===0)return"Exact match";let closeness=ad<=3?"Extremely close":ad<=8?"Very close":ad<=18?"Close":ad<=35?"Far":"Very far";return `${closeness} • ${delta<0?"Higher":"Lower"}`}
 function go(){let g=Math.max(0,Math.min(99,parseInt($("guessInput").value,10)));if(Number.isNaN(g)){setResult("Enter a number from 0 to 99.","bad");return}guesses++;const c=clue(g);history.unshift([g,c]);render();if(g===secret)setResult(`Exact combination found in ${guesses} guesses. Safe opened.`,"good");else if(guesses>=maxGuesses)setResult("Out of guesses. Safe locked.","bad");else setResult(c,"info");$("guessInput").select()}
 $("guessBtn").onclick=go;$("guessInput").onkeydown=e=>{if(e.key==="Enter")go()};function render(){$("gCount").textContent=`Guesses ${guesses}/${maxGuesses}`;$("history").innerHTML=history.map(([g,c])=>`<div class="history-line"><b>${String(g).padStart(2,"0")}</b><span class="clue">${c}</span></div>`).join("")||`<div class="history-line"><b>—</b><span class="clue">No guesses yet</span></div>`;debugText(`Secret: ${String(secret).padStart(2,"0")}`)}render();
}

setupTabs();$("difficulty").addEventListener("change",e=>{difficulty=e.target.value;$("hudDifficulty").textContent=e.target.options[e.target.selectedIndex].text;load(active)});$("resetBtn").onclick=()=>load(active);$("debugToggle").addEventListener("change",e=>debug.classList.toggle("hidden",!e.target.checked));load("dial");
})();
